/* AISummaryButton.jsx */
import React, { useState } from 'react'
import { summarizeMeeting } from '../utils/aiClient'
import { FaBrain, FaMagic, FaCheck, FaExclamationCircle } from 'react-icons/fa'

export default function AISummaryButton({ meetingId, getTranscript }) {
  const [loading, setLoading] = useState(false)
  const [summary, setSummary] = useState(null)
  const [error, setError] = useState(null)
  const [copied, setCopied] = useState(false)

  async function handleSummarize() {
    setError(null)
    setLoading(true)
    try {
      const transcript = await getTranscript()
      if (!transcript || transcript.length < 10) {
        throw new Error("Transcript is too short to summarize.")
      }
      const resp = await summarizeMeeting(meetingId, transcript, { brief: false })
      setSummary(resp.summary_text)
    } catch (err) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  const handleCopy = () => {
    if (summary) {
      navigator.clipboard.writeText(summary)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  return (
    <div className="space-y-4">
      <button 
        onClick={handleSummarize} 
        disabled={loading} 
        className={`w-full group relative overflow-hidden px-6 py-4 rounded-2xl font-bold text-white transition-all transform active:scale-95 flex items-center justify-center gap-3 ${
          loading 
            ? 'bg-slate-800 cursor-not-allowed border border-white/10' 
            : 'bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 hover:shadow-[0_0_20px_rgba(139,92,246,0.5)] border border-white/20'
        }`}
      >
        <div className="absolute inset-0 bg-gradient-to-r from-white/0 via-white/10 to-white/0 translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-1000"></div>
        
        {loading ? (
          <>
            <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-slate-200 to-slate-400">Synthesizing Intellect...</span>
          </>
        ) : (
          <>
            <FaBrain className="text-xl animate-pulse" />
            <span>Generate AISummary™</span>
            <FaMagic className="text-sm opacity-50" />
          </>
        )}
      </button>

      {error && (
        <div className="p-4 bg-red-900/20 border border-red-500/30 rounded-xl flex items-start gap-3 animate-shake">
          <FaExclamationCircle className="text-red-400 mt-1 shrink-0" />
          <div className="text-sm text-red-200 leading-relaxed">{error}</div>
        </div>
      )}

      {summary && (
        <div className="group relative bg-slate-900/60 backdrop-blur-xl border border-white/10 rounded-2xl p-6 shadow-2xl transition-all hover:border-white/20 animate-slideIn">
          <div className="flex items-center justify-between mb-4 border-b border-white/5 pb-4">
            <h4 className="font-bold text-indigo-300 flex items-center gap-2">
              <FaMagic className="text-xs" />
              Executive Insights
            </h4>
            <button 
              onClick={handleCopy}
              className="text-[10px] uppercase tracking-widest px-3 py-1.5 bg-white/5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white transition-all flex items-center gap-2 border border-white/5"
            >
              {copied ? <><FaCheck className="text-green-500" /> Copied</> : 'Copy Text'}
            </button>
          </div>
          <div className="max-h-60 overflow-y-auto custom-scrollbar pr-2">
            <p className="text-sm text-slate-300 leading-relaxed italic whitespace-pre-wrap selection:bg-indigo-500/30">
              {summary}
            </p>
          </div>
          <div className="mt-4 pt-4 border-t border-white/5 text-[10px] text-slate-500 font-medium">
            Generated by Antigravity Core AI • {new Date().toLocaleTimeString()}
          </div>
        </div>
      )}
    </div>
  )
}
