"""add tenant tables

Revision ID: 054245182907
Revises: 
Create Date: 2025-12-29 11:53:13.346111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054245182907'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_messages', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_dm_rooms', 'rooms', ['call_room_id'], ['id'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('scheduled_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_ids', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('retry_interval_seconds', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_workspace_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
        batch_op.alter_column('two_factor_enabled',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('totp_secret',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('totp_encrypted',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.create_foreign_key('fk_users_admin', 'users', ['admin_id'], ['id'])
        batch_op.create_foreign_key('fk_users_last_ws', 'workspaces', ['last_workspace_id'], ['id'])

    with op.batch_alter_table('workspace_domains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))
        batch_op.alter_column('domain',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_index('ix_workspace_domains_domain')
        batch_op.create_unique_constraint('uq_ws_domains_domain', ['domain'])
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_workspaces_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_code'))
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('workspace_domains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_workspace_domains_domain', ['domain'], unique=1)
        batch_op.alter_column('domain',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('verified')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('totp_encrypted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('totp_secret',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('two_factor_enabled',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('status')
        batch_op.drop_column('last_workspace_id')

    with op.batch_alter_table('scheduled_messages', schema=None) as batch_op:
        batch_op.drop_column('retry_interval_seconds')
        batch_op.drop_column('last_error')
        batch_op.drop_column('attempts')
        batch_op.drop_column('file_ids')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('direct_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
