"""add course channels and assignment channel_id

Revision ID: b4c541104e40
Revises: e2ba753aad93
Create Date: 2026-01-04 19:54:50.505820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c541104e40'
down_revision = 'e2ba753aad93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.create_foreign_key(None, 'channels', ['channel_id'], ['id'])

    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_column('course_code')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('channel_id')

    # ### end Alembic commands ###
